# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentCollab < Formula
  desc "P2P-based distributed collaboration system for AI agents"
  homepage "https://github.com/vanillacake369/agent-collab"
  version "0.3.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.1/agent-collab_v0.3.1_darwin_amd64.tar.gz"
      sha256 "d78f1aef424dac81046b396d63b2b316b056bde7b1e5ca50d3a441794fb3172e"

      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.1/agent-collab_v0.3.1_darwin_arm64.tar.gz"
      sha256 "06e8a3184d40b51d064729d20cc1bf99aed6f623426e1fa59d0bfac8dceb580d"

      def install
        bin.install "agent-collab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.1/agent-collab_v0.3.1_linux_amd64.tar.gz"
      sha256 "cd2e324d9e603bd7b0a99317ba4a1f8cf65224c39cb9cf354a50375978eb0a79"
      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.1/agent-collab_v0.3.1_linux_arm64.tar.gz"
      sha256 "a2186d9670089ed592b1fbd13dc8918c3621337c3e6d9fc2b2890bf3ace89da5"
      def install
        bin.install "agent-collab"
      end
    end
  end

  test do
    system "#{bin}/agent-collab", "version"
  end
end
