# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentCollab < Formula
  desc "P2P-based distributed collaboration system for AI agents"
  homepage "https://github.com/vanillacake369/agent-collab"
  version "0.2.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.2.2/agent-collab_v0.2.2_darwin_amd64.tar.gz"
      sha256 "266fb7ff8e461de763cf6ec7cd4920b932283de15cab9bb61cbe32fa13749e5a"

      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.2.2/agent-collab_v0.2.2_darwin_arm64.tar.gz"
      sha256 "f91dfa4f11a04c5fa2a78f0bbdc46319d6372304bc61bc2426195a38255b11e7"

      def install
        bin.install "agent-collab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.2.2/agent-collab_v0.2.2_linux_amd64.tar.gz"
      sha256 "86534e3096cc7dd7740d43ef94714ec090eab1e9d178a7e5e1b8475eaa7012dc"
      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.2.2/agent-collab_v0.2.2_linux_arm64.tar.gz"
      sha256 "5ec8c95cbd917b2abc9b78311250d849dd09b4c6038ab3c93328dea46a29f375"
      def install
        bin.install "agent-collab"
      end
    end
  end

  test do
    system "#{bin}/agent-collab", "version"
  end
end
