# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class AgentCollab < Formula
  desc "P2P-based distributed collaboration system for AI agents"
  homepage "https://github.com/vanillacake369/agent-collab"
  version "0.3.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.0/agent-collab_v0.3.0_darwin_amd64.tar.gz"
      sha256 "890f2c8ced64780673cfa96949b224bd2e6804b74193d1a2ec592fab08eb8b70"

      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.0/agent-collab_v0.3.0_darwin_arm64.tar.gz"
      sha256 "27f74bce095a39f957004001989c2d0700bc41cb25dc4173d6016a0ff35d9529"

      def install
        bin.install "agent-collab"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.0/agent-collab_v0.3.0_linux_amd64.tar.gz"
      sha256 "c3d2f42ddea26ae6b371167401717859ac2e42b2b7afb84fa088c42f248b25bc"
      def install
        bin.install "agent-collab"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/vanillacake369/agent-collab/releases/download/v0.3.0/agent-collab_v0.3.0_linux_arm64.tar.gz"
      sha256 "f6551ccffd9ea2da8bf80daf5728797c65e89ab15c1cf363c55758894f9d9434"
      def install
        bin.install "agent-collab"
      end
    end
  end

  test do
    system "#{bin}/agent-collab", "version"
  end
end
